package peluqueria;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @Michael Naranjo Bautista y Daniel ESteban Rivera Gomez 
 */
public class PeluqueriaWaos extends javax.swing.JFrame {
     
     Peluquero ana= new Peluquero();
     Peluquero roberto=new Peluquero();
     Peluquero jose = new Peluquero();
     Peluquero lucrecia=new Peluquero();
    /**
     * Creates new form PeluqueriaWaos
     */
    public PeluqueriaWaos() {
        initComponents();
       
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iniciarDia = new javax.swing.JButton();
        regristarAnita = new javax.swing.JButton();
        registarRoberto = new javax.swing.JButton();
        registraLucrecia = new javax.swing.JButton();
        registrarJose = new javax.swing.JButton();
        verTotales = new javax.swing.JButton();
        cantCortesCabLucrecia = new javax.swing.JLabel();
        precCorteCabLucrecia = new javax.swing.JLabel();
        precCorteDamLucrecia = new javax.swing.JLabel();
        cantCortesDamLucrecia = new javax.swing.JLabel();
        cantTinturasLucrecia = new javax.swing.JLabel();
        precTinturaLucrecia = new javax.swing.JLabel();
        precPeinadoLucrecia = new javax.swing.JLabel();
        cantPeinadosLucrecia = new javax.swing.JLabel();
        totalServiciosLucrecia = new javax.swing.JLabel();
        totalRecaudadoLucrecia = new javax.swing.JLabel();
        cantCortesCabJose = new javax.swing.JLabel();
        precCorteCabJose = new javax.swing.JLabel();
        precCorteDamJose = new javax.swing.JLabel();
        cantCortesDamJose = new javax.swing.JLabel();
        cantTinturasJose = new javax.swing.JLabel();
        precTinturaJose = new javax.swing.JLabel();
        precPeinadoJose = new javax.swing.JLabel();
        cantPeinadosJose = new javax.swing.JLabel();
        totalServiciosJose = new javax.swing.JLabel();
        totalRecaudadoJose = new javax.swing.JLabel();
        cantCortesCabRoberto = new javax.swing.JLabel();
        precCorteCabRoberto = new javax.swing.JLabel();
        precCorteDamRoberto = new javax.swing.JLabel();
        cantCortesDamRoberto = new javax.swing.JLabel();
        cantTinturasRoberto = new javax.swing.JLabel();
        precTinturaRoberto = new javax.swing.JLabel();
        precPeinadoRoberto = new javax.swing.JLabel();
        cantPeinadosRoberto = new javax.swing.JLabel();
        totalServiciosRoberto = new javax.swing.JLabel();
        totalRecaudadoRoberto = new javax.swing.JLabel();
        precTinturaAnita = new javax.swing.JLabel();
        precPeinadoAnita = new javax.swing.JLabel();
        precCorteCabAnita = new javax.swing.JLabel();
        totalRecaudadoAnita = new javax.swing.JLabel();
        totalServiciosAnita = new javax.swing.JLabel();
        precCorteDamAnita = new javax.swing.JLabel();
        cantTinturasAnita = new javax.swing.JLabel();
        cantPeinadosAnita = new javax.swing.JLabel();
        cantCortesCabAnita = new javax.swing.JLabel();
        cantCortesDamAnita = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        NombreLucrecia = new javax.swing.JLabel();
        NombreJose = new javax.swing.JLabel();
        NombreRoberto = new javax.swing.JLabel();
        NombreAnita = new javax.swing.JLabel();
        Ana = new javax.swing.JLabel();
        Jose = new javax.swing.JLabel();
        Roberto = new javax.swing.JLabel();
        Lucrecia = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        slogan = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        div3 = new javax.swing.JLabel();
        div2 = new javax.swing.JLabel();
        div1 = new javax.swing.JLabel();
        div = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(147, 0, 0));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iniciarDia.setBackground(new java.awt.Color(0, 140, 127));
        iniciarDia.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        iniciarDia.setForeground(new java.awt.Color(24, 61, 61));
        iniciarDia.setText("iniciar dia");
        iniciarDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarDiaActionPerformed(evt);
            }
        });
        getContentPane().add(iniciarDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 570, 85, -1));

        regristarAnita.setBackground(new java.awt.Color(92, 131, 116));
        regristarAnita.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        regristarAnita.setForeground(new java.awt.Color(24, 61, 61));
        regristarAnita.setText("Registrar Anita");
        regristarAnita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regristarAnitaActionPerformed(evt);
            }
        });
        getContentPane().add(regristarAnita, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 570, 112, -1));

        registarRoberto.setBackground(new java.awt.Color(92, 131, 116));
        registarRoberto.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        registarRoberto.setForeground(new java.awt.Color(24, 61, 61));
        registarRoberto.setText("Registrar Roberto");
        registarRoberto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registarRobertoActionPerformed(evt);
            }
        });
        getContentPane().add(registarRoberto, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 570, -1, -1));

        registraLucrecia.setBackground(new java.awt.Color(92, 131, 116));
        registraLucrecia.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        registraLucrecia.setForeground(new java.awt.Color(24, 61, 61));
        registraLucrecia.setText("Registrar Lucrecia");
        registraLucrecia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registraLucreciaActionPerformed(evt);
            }
        });
        getContentPane().add(registraLucrecia, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 570, -1, -1));

        registrarJose.setBackground(new java.awt.Color(92, 131, 116));
        registrarJose.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        registrarJose.setForeground(new java.awt.Color(24, 61, 61));
        registrarJose.setText("Registrar Jose");
        registrarJose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarJoseActionPerformed(evt);
            }
        });
        getContentPane().add(registrarJose, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 570, -1, -1));

        verTotales.setBackground(new java.awt.Color(92, 131, 144));
        verTotales.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        verTotales.setForeground(new java.awt.Color(255, 255, 255));
        verTotales.setText("Ver Totales");
        getContentPane().add(verTotales, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 570, -1, -1));

        cantCortesCabLucrecia.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        cantCortesCabLucrecia.setForeground(new java.awt.Color(255, 255, 255));
        cantCortesCabLucrecia.setText("0");
        getContentPane().add(cantCortesCabLucrecia, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 390, 20, -1));

        precCorteCabLucrecia.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        precCorteCabLucrecia.setForeground(new java.awt.Color(255, 255, 255));
        precCorteCabLucrecia.setText("$ 0");
        getContentPane().add(precCorteCabLucrecia, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 390, 30, -1));

        precCorteDamLucrecia.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        precCorteDamLucrecia.setForeground(new java.awt.Color(255, 255, 255));
        precCorteDamLucrecia.setText("$ 0");
        getContentPane().add(precCorteDamLucrecia, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 410, 30, -1));

        cantCortesDamLucrecia.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        cantCortesDamLucrecia.setForeground(new java.awt.Color(255, 255, 255));
        cantCortesDamLucrecia.setText("0");
        getContentPane().add(cantCortesDamLucrecia, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 410, 10, -1));

        cantTinturasLucrecia.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        cantTinturasLucrecia.setForeground(new java.awt.Color(255, 255, 255));
        cantTinturasLucrecia.setText("0");
        getContentPane().add(cantTinturasLucrecia, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 430, 20, -1));

        precTinturaLucrecia.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        precTinturaLucrecia.setForeground(new java.awt.Color(255, 255, 255));
        precTinturaLucrecia.setText("$ 0");
        getContentPane().add(precTinturaLucrecia, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 430, 30, -1));

        precPeinadoLucrecia.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        precPeinadoLucrecia.setForeground(new java.awt.Color(255, 255, 255));
        precPeinadoLucrecia.setText("$ 0");
        getContentPane().add(precPeinadoLucrecia, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 450, 30, -1));

        cantPeinadosLucrecia.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        cantPeinadosLucrecia.setForeground(new java.awt.Color(255, 255, 255));
        cantPeinadosLucrecia.setText("0");
        getContentPane().add(cantPeinadosLucrecia, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 450, 10, -1));

        totalServiciosLucrecia.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        totalServiciosLucrecia.setForeground(new java.awt.Color(255, 255, 255));
        totalServiciosLucrecia.setText("0");
        getContentPane().add(totalServiciosLucrecia, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 480, 20, -1));

        totalRecaudadoLucrecia.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        totalRecaudadoLucrecia.setForeground(new java.awt.Color(255, 255, 255));
        totalRecaudadoLucrecia.setText("$ 0");
        getContentPane().add(totalRecaudadoLucrecia, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 500, 30, -1));

        cantCortesCabJose.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        cantCortesCabJose.setForeground(new java.awt.Color(255, 255, 255));
        cantCortesCabJose.setText("0");
        getContentPane().add(cantCortesCabJose, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 390, 20, -1));

        precCorteCabJose.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        precCorteCabJose.setForeground(new java.awt.Color(255, 255, 255));
        precCorteCabJose.setText("$ 0");
        getContentPane().add(precCorteCabJose, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, 30, -1));

        precCorteDamJose.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        precCorteDamJose.setForeground(new java.awt.Color(255, 255, 255));
        precCorteDamJose.setText("$ 0");
        getContentPane().add(precCorteDamJose, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 410, 30, -1));

        cantCortesDamJose.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        cantCortesDamJose.setForeground(new java.awt.Color(255, 255, 255));
        cantCortesDamJose.setText("0");
        getContentPane().add(cantCortesDamJose, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 410, 10, -1));

        cantTinturasJose.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        cantTinturasJose.setForeground(new java.awt.Color(255, 255, 255));
        cantTinturasJose.setText("0");
        getContentPane().add(cantTinturasJose, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 430, 20, -1));

        precTinturaJose.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        precTinturaJose.setForeground(new java.awt.Color(255, 255, 255));
        precTinturaJose.setText("$ 0");
        getContentPane().add(precTinturaJose, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 430, 30, -1));

        precPeinadoJose.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        precPeinadoJose.setForeground(new java.awt.Color(255, 255, 255));
        precPeinadoJose.setText("$ 0");
        getContentPane().add(precPeinadoJose, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 450, 30, -1));

        cantPeinadosJose.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        cantPeinadosJose.setForeground(new java.awt.Color(255, 255, 255));
        cantPeinadosJose.setText("0");
        getContentPane().add(cantPeinadosJose, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 450, 10, -1));

        totalServiciosJose.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        totalServiciosJose.setForeground(new java.awt.Color(255, 255, 255));
        totalServiciosJose.setText("0");
        getContentPane().add(totalServiciosJose, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 480, 20, -1));

        totalRecaudadoJose.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        totalRecaudadoJose.setForeground(new java.awt.Color(255, 255, 255));
        totalRecaudadoJose.setText("$ 0");
        getContentPane().add(totalRecaudadoJose, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 500, 30, -1));

        cantCortesCabRoberto.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        cantCortesCabRoberto.setForeground(new java.awt.Color(255, 255, 255));
        cantCortesCabRoberto.setText("0");
        getContentPane().add(cantCortesCabRoberto, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 180, 20, -1));

        precCorteCabRoberto.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        precCorteCabRoberto.setForeground(new java.awt.Color(255, 255, 255));
        precCorteCabRoberto.setText("$ 0");
        getContentPane().add(precCorteCabRoberto, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 180, 30, -1));

        precCorteDamRoberto.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        precCorteDamRoberto.setForeground(new java.awt.Color(255, 255, 255));
        precCorteDamRoberto.setText("$ 0");
        getContentPane().add(precCorteDamRoberto, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 200, 30, -1));

        cantCortesDamRoberto.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        cantCortesDamRoberto.setForeground(new java.awt.Color(255, 255, 255));
        cantCortesDamRoberto.setText("0");
        getContentPane().add(cantCortesDamRoberto, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 200, 10, -1));

        cantTinturasRoberto.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        cantTinturasRoberto.setForeground(new java.awt.Color(255, 255, 255));
        cantTinturasRoberto.setText("0");
        getContentPane().add(cantTinturasRoberto, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 220, 20, -1));

        precTinturaRoberto.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        precTinturaRoberto.setForeground(new java.awt.Color(255, 255, 255));
        precTinturaRoberto.setText("$ 0");
        getContentPane().add(precTinturaRoberto, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 220, 30, -1));

        precPeinadoRoberto.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        precPeinadoRoberto.setForeground(new java.awt.Color(255, 255, 255));
        precPeinadoRoberto.setText("$ 0");
        getContentPane().add(precPeinadoRoberto, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 240, 30, -1));

        cantPeinadosRoberto.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        cantPeinadosRoberto.setForeground(new java.awt.Color(255, 255, 255));
        cantPeinadosRoberto.setText("0");
        getContentPane().add(cantPeinadosRoberto, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 240, 10, -1));

        totalServiciosRoberto.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        totalServiciosRoberto.setForeground(new java.awt.Color(255, 255, 255));
        totalServiciosRoberto.setText("0");
        getContentPane().add(totalServiciosRoberto, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 280, 20, -1));

        totalRecaudadoRoberto.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        totalRecaudadoRoberto.setForeground(new java.awt.Color(255, 255, 255));
        totalRecaudadoRoberto.setText("$ 0");
        getContentPane().add(totalRecaudadoRoberto, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 300, 30, -1));

        precTinturaAnita.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        precTinturaAnita.setForeground(new java.awt.Color(255, 255, 255));
        precTinturaAnita.setText("$ 0");
        getContentPane().add(precTinturaAnita, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, 130, -1));

        precPeinadoAnita.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        precPeinadoAnita.setForeground(new java.awt.Color(255, 255, 255));
        precPeinadoAnita.setText("$ 0");
        getContentPane().add(precPeinadoAnita, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, 120, -1));

        precCorteCabAnita.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        precCorteCabAnita.setForeground(new java.awt.Color(255, 255, 255));
        precCorteCabAnita.setText("$ 0");
        getContentPane().add(precCorteCabAnita, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 110, -1));

        totalRecaudadoAnita.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        totalRecaudadoAnita.setForeground(new java.awt.Color(255, 255, 255));
        totalRecaudadoAnita.setText("$ 0");
        getContentPane().add(totalRecaudadoAnita, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, 120, -1));

        totalServiciosAnita.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        totalServiciosAnita.setForeground(new java.awt.Color(255, 255, 255));
        totalServiciosAnita.setText("0");
        getContentPane().add(totalServiciosAnita, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, 90, -1));

        precCorteDamAnita.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        precCorteDamAnita.setForeground(new java.awt.Color(255, 255, 255));
        precCorteDamAnita.setText("$ 0");
        getContentPane().add(precCorteDamAnita, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 120, -1));

        cantTinturasAnita.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        cantTinturasAnita.setForeground(new java.awt.Color(255, 255, 255));
        cantTinturasAnita.setText("0");
        getContentPane().add(cantTinturasAnita, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 50, -1));

        cantPeinadosAnita.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        cantPeinadosAnita.setForeground(new java.awt.Color(255, 255, 255));
        cantPeinadosAnita.setText("0");
        getContentPane().add(cantPeinadosAnita, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 50, -1));

        cantCortesCabAnita.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        cantCortesCabAnita.setForeground(new java.awt.Color(255, 255, 255));
        cantCortesCabAnita.setText("0");
        getContentPane().add(cantCortesCabAnita, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 60, -1));

        cantCortesDamAnita.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        cantCortesDamAnita.setForeground(new java.awt.Color(255, 255, 255));
        cantCortesDamAnita.setText("0");
        getContentPane().add(cantCortesDamAnita, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 50, -1));

        jLabel23.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("total servicios:");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 480, -1, -1));

        jLabel24.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("total recaudado:");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 500, -1, -1));

        jLabel21.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("total servicios:");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 480, -1, -1));

        jLabel22.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("total recaudado:");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 500, -1, -1));

        jLabel19.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("total servicios:");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 280, -1, -1));

        jLabel20.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("total recaudado:");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 300, -1, -1));

        jLabel18.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("total recaudado:");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("total servicios:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("tinturas cabello:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 440, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("corte caballero:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 400, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("peinados");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 460, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("corte Dama:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 420, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("tinturas cabello:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("corte caballero:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("peinados");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 450, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("corte Dama:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("corte caballero:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 180, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("corte Dama:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 200, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("tinturas cabello:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 220, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("peinados");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 240, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("peinados");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("tinturas cabello:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("corte Dama:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("corte caballero:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, -1, -1));

        NombreLucrecia.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        NombreLucrecia.setForeground(new java.awt.Color(255, 255, 255));
        NombreLucrecia.setText("Lucrecia");
        getContentPane().add(NombreLucrecia, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 370, -1, -1));

        NombreJose.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        NombreJose.setForeground(new java.awt.Color(255, 255, 255));
        NombreJose.setText("Jose");
        getContentPane().add(NombreJose, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, -1, -1));

        NombreRoberto.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        NombreRoberto.setForeground(new java.awt.Color(255, 255, 255));
        NombreRoberto.setText("Roberto");
        getContentPane().add(NombreRoberto, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 150, -1, -1));

        NombreAnita.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        NombreAnita.setForeground(new java.awt.Color(255, 255, 255));
        NombreAnita.setText("Anita");
        getContentPane().add(NombreAnita, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, -1, -1));

        Ana.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Documents\\Desarrollo\\programacion 301\\actividad peluqueria\\Peluqueria\\src\\main\\java\\imagenes\\barbera2.jpeg")); // NOI18N
        getContentPane().add(Ana, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 190, 180));

        Jose.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Documents\\Desarrollo\\programacion 301\\actividad peluqueria\\Peluqueria\\src\\main\\java\\imagenes\\barbero.jpeg")); // NOI18N
        getContentPane().add(Jose, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 190, 180));

        Roberto.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Documents\\Desarrollo\\programacion 301\\actividad peluqueria\\Peluqueria\\src\\main\\java\\imagenes\\barbero2.jpeg")); // NOI18N
        Roberto.setLabelFor(Roberto);
        Roberto.setAutoscrolls(true);
        getContentPane().add(Roberto, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 150, 190, 180));

        Lucrecia.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Documents\\Desarrollo\\programacion 301\\actividad peluqueria\\Peluqueria\\src\\main\\java\\imagenes\\barbera.jpeg")); // NOI18N
        getContentPane().add(Lucrecia, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 360, 190, 180));

        logo.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Documents\\Desarrollo\\programacion 301\\actividad peluqueria\\Peluqueria\\src\\main\\java\\imagenes\\logo.png")); // NOI18N
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, -1, -1));

        slogan.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        slogan.setForeground(new java.awt.Color(24, 61, 61));
        slogan.setText("\"Mas que una barberia, una experiencia\"");
        getContentPane().add(slogan, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, -1, -1));

        titulo.setFont(new java.awt.Font("Monospaced", 1, 60)); // NOI18N
        titulo.setForeground(new java.awt.Color(24, 61, 61));
        titulo.setText("Barberia Waos");
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 490, -1));

        div3.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Documents\\Desarrollo\\programacion 301\\actividad peluqueria\\Peluqueria\\src\\main\\java\\imagenes\\contenedor.jpg")); // NOI18N
        getContentPane().add(div3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 350, 480, 200));

        div2.setForeground(new java.awt.Color(255, 255, 255));
        div2.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Documents\\Desarrollo\\programacion 301\\actividad peluqueria\\Peluqueria\\src\\main\\java\\imagenes\\contenedor.jpg")); // NOI18N
        getContentPane().add(div2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 140, 480, 200));

        div1.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Documents\\Desarrollo\\programacion 301\\actividad peluqueria\\Peluqueria\\src\\main\\java\\imagenes\\contenedor.jpg")); // NOI18N
        getContentPane().add(div1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 510, 200));

        div.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Documents\\Desarrollo\\programacion 301\\actividad peluqueria\\Peluqueria\\src\\main\\java\\imagenes\\contenedor.jpg")); // NOI18N
        getContentPane().add(div, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 510, 200));

        fondo.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Documents\\Desarrollo\\programacion 301\\actividad peluqueria\\Peluqueria\\src\\main\\java\\imagenes\\fondo 2.jpg")); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1070, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regristarAnitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regristarAnitaActionPerformed
        // TODO add your handling code here:
        ana=ana.ingresarDatosPeluquero("Ana","Ramirez",56);
        //caballero
        cantCortesCabAnita.setText(""+ana.getCantCortesCaballero());
        precCorteCabAnita.setText("$ "+ana.getTotalCortesCaballero());
        //dama
        cantCortesDamAnita.setText(""+ana.getCantCortesDama());
        precCorteDamAnita.setText("$ "+ana.getTotalCortesDama());
        //tinturas
        cantTinturasAnita.setText(""+ana.getCantTinturasCabello());
        precTinturaAnita.setText("$ "+ana.getTotalTinturasCabello());
        //peinados
        cantPeinadosAnita.setText(""+ana.getCantPeinados());
        precPeinadoAnita.setText("$ "+ana.getTotalPeinados());
        //servicios y recaudos
        ana.setTotalServicios(ana.getTotalServicios()+ana.calcularTotalServicios());
        totalServiciosAnita.setText(""+ana.getTotalServicios());
        ana.setTotalRecaudado(ana.getTotalRecaudado()+ana.calcularTotalRecaudado());
        totalRecaudadoAnita.setText("$ "+ana.getTotalRecaudado());
    }//GEN-LAST:event_regristarAnitaActionPerformed

    private void registarRobertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registarRobertoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registarRobertoActionPerformed

    private void registraLucreciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registraLucreciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registraLucreciaActionPerformed

    private void registrarJoseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarJoseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registrarJoseActionPerformed

    private void iniciarDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarDiaActionPerformed
        cantCortesCabAnita.setText(""+0);
        cantCortesDamAnita.setText(""+0);
        cantTinturasAnita.setText(""+0);
        cantPeinadosAnita.setText(""+0);
        totalServiciosAnita.setText(""+0);
        totalRecaudadoAnita.setText("$ "+0);
        precCorteCabAnita.setText("$ "+0);
        precCorteDamAnita.setText("$ "+0);
        precPeinadoAnita.setText("$ "+0);
        precTinturaAnita.setText("$ "+0);
        //Roberto
        cantCortesCabRoberto.setText(""+0);
        cantCortesDamRoberto.setText(""+0);
        cantTinturasRoberto.setText(""+0);
        cantPeinadosRoberto.setText(""+0);
        totalServiciosRoberto.setText(""+0);
        totalRecaudadoRoberto.setText("$ "+0);
        precCorteCabRoberto.setText("$ "+0);
        precCorteDamRoberto.setText("$ "+0);
        precPeinadoRoberto.setText("$ "+0);
        precTinturaRoberto.setText("$ "+0);
        //Jose
        cantCortesCabJose.setText(""+0);
        cantCortesDamJose.setText(""+0);
        cantTinturasJose.setText(""+0);
        cantPeinadosJose.setText(""+0);
        totalServiciosJose.setText(""+0);
        totalRecaudadoJose.setText("$ "+0);
        precCorteCabJose.setText("$ "+0);
        precCorteDamJose.setText("$ "+0);
        precPeinadoJose.setText("$ "+0);
        precTinturaJose.setText("$ "+0);
        //Lucrecia
        cantCortesCabLucrecia.setText(""+0);
        cantCortesDamLucrecia.setText(""+0);
        cantTinturasLucrecia.setText(""+0);
        cantPeinadosLucrecia.setText(""+0);
        totalServiciosLucrecia.setText(""+0);
        totalRecaudadoLucrecia.setText("$ "+0);
        precCorteCabLucrecia.setText("$ "+0);
        precCorteDamLucrecia.setText("$ "+0);
        precPeinadoLucrecia.setText("$ "+0);
        precTinturaLucrecia.setText("$ "+0);
      //ana.iniciarDia();
        ana.iniciarDia();
        roberto.iniciarDia();
        jose.iniciarDia();
        lucrecia.iniciarDia();
    }//GEN-LAST:event_iniciarDiaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel 
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PeluqueriaWaos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PeluqueriaWaos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PeluqueriaWaos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PeluqueriaWaos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PeluqueriaWaos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Ana;
    private javax.swing.JLabel Jose;
    private javax.swing.JLabel Lucrecia;
    private javax.swing.JLabel NombreAnita;
    private javax.swing.JLabel NombreJose;
    private javax.swing.JLabel NombreLucrecia;
    private javax.swing.JLabel NombreRoberto;
    private javax.swing.JLabel Roberto;
    private javax.swing.JLabel cantCortesCabAnita;
    private javax.swing.JLabel cantCortesCabJose;
    private javax.swing.JLabel cantCortesCabLucrecia;
    private javax.swing.JLabel cantCortesCabRoberto;
    private javax.swing.JLabel cantCortesDamAnita;
    private javax.swing.JLabel cantCortesDamJose;
    private javax.swing.JLabel cantCortesDamLucrecia;
    private javax.swing.JLabel cantCortesDamRoberto;
    private javax.swing.JLabel cantPeinadosAnita;
    private javax.swing.JLabel cantPeinadosJose;
    private javax.swing.JLabel cantPeinadosLucrecia;
    private javax.swing.JLabel cantPeinadosRoberto;
    private javax.swing.JLabel cantTinturasAnita;
    private javax.swing.JLabel cantTinturasJose;
    private javax.swing.JLabel cantTinturasLucrecia;
    private javax.swing.JLabel cantTinturasRoberto;
    private javax.swing.JLabel div;
    private javax.swing.JLabel div1;
    private javax.swing.JLabel div2;
    private javax.swing.JLabel div3;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton iniciarDia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel precCorteCabAnita;
    private javax.swing.JLabel precCorteCabJose;
    private javax.swing.JLabel precCorteCabLucrecia;
    private javax.swing.JLabel precCorteCabRoberto;
    private javax.swing.JLabel precCorteDamAnita;
    private javax.swing.JLabel precCorteDamJose;
    private javax.swing.JLabel precCorteDamLucrecia;
    private javax.swing.JLabel precCorteDamRoberto;
    private javax.swing.JLabel precPeinadoAnita;
    private javax.swing.JLabel precPeinadoJose;
    private javax.swing.JLabel precPeinadoLucrecia;
    private javax.swing.JLabel precPeinadoRoberto;
    private javax.swing.JLabel precTinturaAnita;
    private javax.swing.JLabel precTinturaJose;
    private javax.swing.JLabel precTinturaLucrecia;
    private javax.swing.JLabel precTinturaRoberto;
    private javax.swing.JButton registarRoberto;
    private javax.swing.JButton registraLucrecia;
    private javax.swing.JButton registrarJose;
    private javax.swing.JButton regristarAnita;
    private javax.swing.JLabel slogan;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel totalRecaudadoAnita;
    private javax.swing.JLabel totalRecaudadoJose;
    private javax.swing.JLabel totalRecaudadoLucrecia;
    private javax.swing.JLabel totalRecaudadoRoberto;
    private javax.swing.JLabel totalServiciosAnita;
    private javax.swing.JLabel totalServiciosJose;
    private javax.swing.JLabel totalServiciosLucrecia;
    private javax.swing.JLabel totalServiciosRoberto;
    private javax.swing.JButton verTotales;
    // End of variables declaration//GEN-END:variables
}
